# Generated by Django 4.0.3 on 2022-07-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('disPlayInMenu', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('url', models.URLField(blank=True)),
                ('urlClean', models.CharField(blank=True, max_length=100)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.project')),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.project_tag')),
            ],
        ),
        migrations.CreateModel(
            name='File_pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='portfolio/pdfs')),
                ('main_resume', models.BooleanField(default=False, help_text='set only one pdf as the main pdf for the main page')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/pdfs')),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.project_tag')),
            ],
        ),
    ]
